version : “3”

services:
  db:
    container_name: review_cock_db
    restart: always
    image: mariadb
    ports:
      - 3307:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: review_cock
      MYSQL_USER: rvc
      MYSQL_PASSWORD: rvc
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
